import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { useState } from 'react'
import Image from 'next/image'
import FeaturedProducts from '../components/FeaturedProducts'
import FeaturedCountries from '../components/FeaturedCountries'
import FeaturedEmployees from '../components/FeaturedEmployees'
import Hero from '../components/Hero'
import Form from '../components/Form'
import countriesObject from '../data/countries.json'
import hotelsObject from '../data/hotels.json'
import employeesObject from '../data/employees.json'

export default function Home() {
	const { countries } = countriesObject
	const { hotels } = hotelsObject
	const { employees } = employeesObject
	const [toggled, setToggled] = useState(false)
	const toggle = () => {
		if (toggled) {
			document.getElementById('grid').style.maxHeight = '47vh'
			document.getElementById('faded').style.filter = 'opacity(1)'
			document.getElementById('faded').style.zIndex = '1'
		} else {
			document.getElementById('grid').style.maxHeight = '300vh'
			document.getElementById('faded').style.filter = 'opacity(0)'
			document.getElementById('faded').style.zIndex = '-1'
		}
		setToggled(!toggled)
	}
	return (
		<>
			<Head>
				<title>Lorem Travels</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.wrapper}>
				<Hero />
				<div className={styles.width}>
					<div className='header'>
						<Image src='/price_tag2.png' height={60} width={60} alt='Tag Icon' />
						<h2>Featured</h2>
						<span>products</span>
					</div>
					<FeaturedProducts hotels={hotels} />
					<div className='header'>
						<Image src='/airplane_icon.png' height={60} width={60} alt='Airplane Icon' />
						<h2>Destinations</h2>
					</div>
					<FeaturedCountries countries={countries} />
					<button onClick={toggle} id={styles.toggleButton}>
						<Image src='/Down_arrowhead.png' width={35} height={35} />
					</button>
					<div className='header'>
						<Image src='/team.png' height={60} width={60} alt='Team Icon' />
						<h2>Our team of </h2>
						<span>experts</span>
					</div>
					<div className={styles.employeesContainer}>
						<FeaturedEmployees employees={employees} />
						<Form />
					</div>
				</div>
			</div>
		</>
	)
}

// {setTimeout(() => {
// 	document.getElementById('toggleButton').scrollIntoView({behavior: 'smooth', block: 'end'})
// 	}, 250)